### ISSUE TITLE
[Critical] Can't place order as guest.

### ISSUE THREAD

**Issue by JeroenGerth** [Vendic/hyva-checkout-newsletter-subscribe#11]
After installing this module it is impossible to place an order as a guest (non-registered customer) when checking the checkbox to sign up for the newsletter. It trows this order in a module.

It looks like it needs a customer ID, but as a guest, of course there is no customer ID and it breaks. Why does it need a customer ID?

<img width="2295" alt="Scherm­afbeelding 2024-08-20 om 11 04 48" src="https://github.com/user-attachments/assets/2995154e-df53-47af-86a3-b413a1e6e3cf">

**Comment by Tjitse-E** [comment]
Hmm strange, this function https://github.com/Vendic/hyva-checkout-newsletter-subscribe/blob/develop/Plugin/AddSubscriberToNewsletter.php#L53-L56 should prevent that from happening. Can you add a breakpoint there and see why this is happening for guests users?
