### ISSUE TITLE
Checkbox issue

### ISSUE THREAD

**Issue by eneskirca** [Vendic/hyva-checkout-newsletter-subscribe#5]
The checkbox disappears after selection, causing errors for guest orders, and registered customers do not complete the signup process.

The following is the current situation:
https://www.awesomescreenshot.com/video/30107823?key=f774f0fcb90d3baeb52ac0227de1927e

**Comment by JeroenGerth** [comment]
I can confirm the issues @eneskirca is mentioning. I have the exact same problems in my project.

**Comment by xavierojeda** [comment]
I can also confirm that the field disappears once the checkbox is selected.

**Comment by eneskirca** [comment]
I've solved my version; you can try it in my pull request. (https://github.com/Vendic/hyva-checkout-newsletter-subscribe/pull/6/files) , I am not sure it it is best way but works on my end

**Comment by JeroenGerth** [comment]
@eneskirca Seems to only solve the issue with the checkbox. Does the module work for you? I can't place an order as guest (error seems to indicate it needs an clientId which doesn't exist for guestorders) and registered users don't even get subscribed even though the checkbox is checked.
